### ISSUE TITLE
Using on OpenOSRS

### ISSUE THREAD

**Issue by AlexisDiazG** [AaronPoon/essence-running#6]
Hi, i been having problem importing this plugin on Open-OSRS, can you help me with this.

https://gyazo.com/9648c37589b41818e3a9964634342100

https://gyazo.com/a0f84835aeb4f4a7b73fc0b6a026d1aa

https://gyazo.com/c192cac5f6c6a50eea4beb07e912e93d

**Comment by AaronPoon** [comment]
This was written using the RuneLite plugin-hub platform. The behavior for other clients is undefined.
